ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - sharp

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - "@upleveled/*"
  - eslint-config-upleveled
  - stylelint-config-upleveled

onlyBuiltDependencies:
  - unrs-resolver

strictDepBuilds: true
