export const metadata = {
  title: 'Contact',
  description: 'Contact',
};
export default function Page() {
  return (
    <main className="bg-gray-50  antialiased dark:bg-gray-900 flex-grow  w-full max-w-full px-5 xl:px-48 sm:px-20 py-12">
      <h1 className="mb-4 text-4xl text-center">About </h1>
      <section className="py-8 antialiased  md:py-16     text-xl  font-normal   sm:px-16 xl:px-48 dark:text-gray-400">
        <div className="mx-auto max-w-screen-xl px-4 2xl:px-0">
          <p>
            <strong>eStores</strong> is a dynamic online marketplace designed to connect buyers and sellers for the exchange of a wide variety of products.
          </p>
          <p className="py-8   text-red-600   ">
              *This project is a portfolio  project showcasing technical skills in Next.js, React, and PostgreSQL.
              It is not a functional online marketplace and does not offer real products or services.
          </p>
          <p> The text on this website was generated by AI.</p>
          <p>
            All images come from Pexels and Pixabay, which provide free stock photos.
          </p>
        </div>
      </section>
    </main>
  );
}
